
<?php
    //to upload question and answers in bulk from  a csv fie to the database
    // called by bulkQimport.php form
	//created by: jitendra dayma
	// ccreated on: 04-04-2016
    // modified by: jitendra dayma
    // modified on :28-04-2016 
	//modification : Changed condition of loop, now Loop runs for 4 times in place of 5 times. and condition in switch case

	//Connect to Database


	include_once('../../service/common/db_connection.php');
	
	// Inititate Log4php logger
	include_once('../../lib/log4php/Logger.php');
	Logger::configure('../../config/log_config.xml');
	$log = Logger::getLogger('upload.php');
	
	$log->debug("****START - upload.php****");

	//Upload File
	if (isset($_POST['submit'])) {
	if (is_uploaded_file($_FILES['filename']['tmp_name'])) {
		echo "<h1>" . "File ". $_FILES['filename']['name'] ." uploaded successfully." . "</h1>";
		echo "<h2>Displaying contents:</h2>";
		readfile($_FILES['filename']['tmp_name']);
	}

	//Import uploaded file to Database
	$handle = fopen($_FILES['filename']['tmp_name'], "r"); 
    try{
    	// begin transaction
    	mysqli_begin_transaction($connection);
    	
    	// stop autocommit
    	mysqli_autocommit($connection, FALSE);

    	// automatically detect line ending in csv file enabled
    	ini_set('auto_detect_line_endings', true);
		
		while (($data = fgetcsv($handle, 8000, ",")) !== FALSE) {
			// Make sure all data is inserted in capital case
			$import="INSERT INTO t_qbank(q_type_code,
									q_description,
									q_weightage,
									q_category,
									q_video,
									q_picture,
									q_lang_code,
									q_authorname,
									q_created_by,
									q_modified_by,
									q_modified_time,
									q_create_time) 
								values('L','$data[0]',1,'NULL','NULL','NULL','en','global','global','NULL','NULL',NOW())";

			$result = mysqli_query($connection,$import);
		    if($result == FALSE)
									{
										throw new Exception($result);
									}

			$log->debug("****question bank related query excecuted****");
			//it will get last inserted autogenerated id for qid in this connection 
			$q_id =mysqli_insert_id($connection);
			// Insert answers of last entered question 
			for($i=1; $i<5; $i++){          
			$import= "INSERT INTO t_ansbank(qid,
											a_code,
											a_sortorder,
											a_lang_code,
											a_desc,
											a_iscorrect,
											a_scaleid,
											a_created_by,
											a_modified_by,
											a_create_time,
											a_modified_time)
										VALUES('$q_id', 'A.$i', '$i', 'en', '$data[$i]','0','0', 'global', 'NULL',NOW(),'NULL')";
			$result = mysqli_query($connection, $import);
			if($result == FALSE)
									{
										throw new Exception($result);
									}

			}
			// change the value of correct answer from char to integer
			switch ($data[5]) {
    			case "A":
        			$ans=1;
        			break;
    			case "B":
        			$ans=2;
        			break;
    			case "C":
        			$ans=3;
        			break;
        		case "D":
        			$ans=4;
        			break;
        		case "E":
        			$ans=5;
        			break;		
    			default:
        			echo "CSV file doen't have data or check the format of data";
			}
			$modification ="UPDATE t_ansbank
			 			 	SET a_iscorrect=1
			 			 	WHERE ( a_sortorder= $ans ) AND ( qid = $q_id ) ";							
			$update_ans=mysqli_query($connection, $modification);
			
			if($update_ans == FALSE)
									{
										throw new Exception($update_ans);
									}
			$log->debug("****update query excecuted****");						
			//make the relation between pc and question
			$select_pc = "SELECT pc_id 
			              FROM t_pc
			              WHERE pc_name = 'General Awareness'";
			$pc_id_query = mysqli_query($connection, $select_pc);
			// as we can't use mysqli result directly so to fetch correct pc id from resul object of mysqli
			$pc_id_array=mysqli_fetch_assoc($pc_id_query);
            $pc_id=$pc_id_array['pc_id'];             	
			$import_pc = "INSERT INTO r_pc_q(qid,
										pc_id,
										created_by,
										modified_by,
										created_time,
										modified_time) 
								VALUES ('$q_id','$pc_id','global','NULL',NOW(),'NULL')";				
			$result = mysqli_query($connection, $import_pc);
			if($result == FALSE)
									{
										throw new Exception($result);
									}	
			$log->debug("****insert query of relation table    excecuted****");					
		}
		mysqli_commit($connection);
		echo "success";	
		$log->debug("****commit called****");

	}
	catch(Exception $e){
		mysqli_rollback($connection);
		$log->debug("****rollback called****");
	}


	fclose($handle);
    //view upload form
}
//close the connection
mysqli_close($connection);
$log->debug("****END - upload.php****");
?>